Create elixir.yml
lawik/noted pull request #10
Opened 2021-05-25 19:04 UTC by m13m

2021-08-26 11:56 UTC, m13m commented
closes #14

2021-08-27 09:36 UTC, lawik requested changes
A few things :) Nothing big. Good job

2021-08-27 09:36 UTC, lawik commented on README.md
> +# Noted [![Elixir CI](https://github.com/m13m/noted/actions/workflows/elixir.yml/badge.svg?branch=main)](https://github.com/m13m/noted/actions/workflows/elixir.yml)
References to the wrong repo :)

2021-08-27 09:36 UTC, lawik commented on config/prod.secret.exs
> +  System.get_env("DATABASE_URL") ||"database.db" ||
It should just raise I think. Though this probably isn't used when we do a release. Probably fix it and make sure it still passes :)

2021-08-27 09:36 UTC, lawik commented on test/noted/telegram/bot_test.exs
> +  @tag :skip
Are these tests broken or why are they skipped now?

2021-09-04 04:43 UTC, m13m commented on test/noted/telegram/bot_test.exs
> +  @tag :skip
not all the tests but these two specific tests.

2022-10-04 17:29 UTC, closed without merging